version: '3'
services:
  school:
    build: .
    ports:
    - "9090:9090"
    depends_on:
      - db
  universitydb:
    image: postgres:10
    restart: always
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_service

